---
- src: https://github.com/open-io/ansible-role-openio-repository.git
  version: "18.10"
  name: repository

- src: https://github.com/open-io/ansible-role-openio-gridinit.git
  version: "18.10"
  name: gridinit

- src: https://github.com/open-io/ansible-role-openio-users.git
  version: "18.10"
  name: users

- src: https://github.com/open-io/ansible-role-openio-memcached.git
  version: "18.10"
  name: memcached

- src: https://github.com/open-io/ansible-role-openio-keystone.git
  version: "18.10"
  name: keystone
...
