# Test playbook
---
- name: generate docker redis group
  hosts: all
  gather_facts: false
  tasks:
    - add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        openio_bind_address: "{{ item.ip }}"
        ansible_eth0:
          ipv4:
            address: "{{ item.ip }}"
        groups: redis
      with_items:
        - { name: "node1", ip: "172.17.0.2" }
        #- { name: "node2", ip: "172.17.0.3" }
        #- { name: "node3", ip: "172.17.0.4" }
      delegate_to: localhost
      run_once: true
      changed_when: false

- hosts: localhost
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: users
    - role: repository
      openio_repository_mirror_host: mirror2.openio.io
      openio_repository_no_log: false
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      #openio_gridinit_per_ns: true
    - role: memcached
      openio_memcached_namespace: "{{ NS }}"
    - role: role_under_test
      openio_oioswift_namespace: "{{ NS }}"
      openio_oioswift_bind_interface: "{{ ansible_default_ipv4.alias }}"
      openio_oioswift_sds_proxy_url: "http://172.17.0.2:6006"   # docker image
      openio_oioswift_workers: 1
      # The following namespace is not the above one "{{ NS }}", but the one from the docker image
      openio_oioswift_sds_proxy_namespace: OPENIO   # docker image
      openio_oioswift_pipeline: "{{ pipeline_tempauth_iam }}"
      openio_oioswift_iam_policy:
        'travis:ci':
          Statement:
            - Sid: FullAccess
              Action:
                - 's3:*'
              Effect: Allow
              Resource:
                - '*'
        'travis:user1':
          Statement:
            - Sid: User1BucketAllObjects
              Action:
                - 's3:ListBucket'
                #- 's3:GetObject'
                - 's3:PutObject'
                - 's3:DeleteObject'
              Effect: Allow
              Resource:
                - '*'
        'plop:user1':
          Statement:
            - Sid: FullAccess
              Action:
                - 's3:*'
              Effect: Allow
              Resource:
                - '*'

      openio_oioswift_filter_tempauth:
        use: "egg:swift#tempauth"
        user_travis_ci: "TRAVIS_PASS .admin"
        user_travis_user1: "USER1_PASS .admin"
        user_plop_user1: "USER1_PASS .admin"
...
